import { Cinema, Hall, Movie, Showtime, Staff, Genre } from '@/types/index';

export const mockCinemas: Cinema[] = [
  {
    id: 'c_hcm_001',
    name: 'CGV Vincom Landmark 81',
    address: 'Tầng 5, TTTM Vincom Center Landmark 81, 720A Điện Biên Phủ',
    city: 'Hồ Chí Minh City',
    district: 'Quận Bình Thạnh',
    phone: '028 3933 1111',
    email: 'landmark81@cgv.vn',
    website: 'https://www.cgv.vn',
    latitude: 10.7937,
    longitude: 106.721,
    description: 'Rạp chiếu phim cao cấp với công nghệ IMAX lớn nhất Việt Nam.',
    amenities: ['IMAX', 'Lounge', '4DX', 'SweetBox'],
    facilities: { parking: 'Basement B2-B4', wifi: true },
    images: ['url_to_landmark81_img1.jpg', 'url_to_landmark81_img2.jpg'],
    virtualTour360Url: 'url_360_landmark81',
    rating: 4.8,
    totalReviews: 3500,
    operatingHours: { mon_sun: '9:00 - 24:00' },
    socialMedia: { facebook: 'cgvlandmark81' },
    status: 'ACTIVE',
    timezone: 'Asia/Ho_Chi_Minh',
    createdAt: '2018-01-15T10:00:00Z',
    updatedAt: '2025-07-01T14:30:00Z',
  },
  {
    id: 'c_hn_002',
    name: 'Lotte Cinema Cầu Giấy',
    address: 'Tầng 6, Lotte Mart, 241 Xuân Thủy',
    city: 'Hà Nội',
    district: 'Quận Cầu Giấy',
    phone: '024 3788 2222',
    email: 'caugiau@lottecinema.vn',
    website: 'https://www.lottecinema.vn',
    latitude: 21.037,
    longitude: 105.78,
    description: 'Rạp chiếu phim lớn, tiện lợi cho khu vực phía Tây Hà Nội.',
    amenities: ['Standard', 'CineComfort'],
    facilities: { parking: 'Basement B1', wifi: true },
    images: ['url_to_caugiau_img1.jpg'],
    rating: 4.1,
    totalReviews: 1800,
    operatingHours: { mon_sun: '9:30 - 23:30' },
    socialMedia: {},
    status: 'ACTIVE',
    timezone: 'Asia/Ho_Chi_Minh',
    createdAt: '2015-05-20T09:00:00Z',
    updatedAt: '2025-06-28T10:00:00Z',
  },
  {
    id: 'c_dn_003',
    name: 'Galaxy Cinema Đà Nẵng',
    address: '46 Trần Phú, Phường Hải Châu 1',
    city: 'Đà Nẵng',
    district: 'Quận Hải Châu',
    phone: '0236 389 7777',
    email: 'danang@galaxycine.vn',
    description: 'Rạp chiếu phim đang trong giai đoạn bảo trì.',
    amenities: ['Standard'],
    facilities: {},
    images: [],
    rating: 3.5,
    totalReviews: 50,
    operatingHours: { mon_fri: 'Tạm dừng', sat_sun: 'Tạm dừng' },
    socialMedia: {},
    status: 'MAINTENANCE',
    timezone: 'Asia/Ho_Chi_Minh',
    createdAt: '2019-11-01T11:00:00Z',
    updatedAt: '2025-07-05T08:00:00Z',
  },
];


export const mockHalls: Hall[] = [
  {
    id: 'h_lm81_imax',
    cinemaId: 'c_hcm_001',
    name: 'Hall 1 - IMAX Laser',
    type: 'IMAX',
    capacity: 350,
    rows: 15,
    screenType: 'Giant Screen',
    soundSystem: '12-Channel Sound',
    features: ['3D capable', 'Wheelchair access'],
    layoutType: 'STADIUM',
    status: 'ACTIVE',
    createdAt: '2018-01-15T11:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'h_lm81_premium',
    cinemaId: 'c_hcm_001',
    name: 'Hall 5 - L\'amour Premium',
    type: 'PREMIUM',
    capacity: 50,
    rows: 5,
    screenType: 'Standard',
    soundSystem: 'Dolby 7.1',
    features: ['Recliner Seats', 'Blankets'],
    layoutType: 'STANDARD',
    status: 'ACTIVE',
    createdAt: '2018-01-15T11:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'h_caugiau_std',
    cinemaId: 'c_hn_002',
    name: 'Hall 3 - Standard',
    type: 'STANDARD',
    capacity: 180,
    rows: 12,
    screenType: 'Standard',
    soundSystem: 'Dolby Digital',
    features: ['Popcorn & Drink holders'],
    layoutType: 'STANDARD',
    status: 'ACTIVE',
    createdAt: '2015-05-20T10:00:00Z',
    updatedAt: '2025-06-15T10:00:00Z',
  },
];


export const mockGenres: Genre[] = [
  { id: 'g_001', name: 'Action' },
  { id: 'g_002', name: 'Thriller' },
  { id: 'g_003', name: 'Biography' },
  { id: 'g_004', name: 'Drama' },
  { id: 'g_005', name: 'History' },
  { id: 'g_006', name: 'Sci-Fi' },
  { id: 'g_007', name: 'Adventure' },
];

export const mockMovies: Movie[] = [
  {
    id: 'm_001',
    title: 'Mission: Impossible - Dead Reckoning Part One',
    originalTitle: 'Mission: Impossible - Dead Reckoning Part One',
    overview: 'Ethan Hunt và nhóm IMF đối mặt với một vũ khí nguy hiểm mới có khả năng đe dọa toàn nhân loại.',
    posterUrl: 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/7/0/700x1000_7_.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=avz06PDqDbM',
    runtime: 163,
    ageRating: 'T13',
    productionCountry: 'US',
    languageType: 'SUBTITLE',
    originalLanguage: 'en',
    spokenLanguages: ['en'],
    genre: [mockGenres[0], mockGenres[1]],
    cast: [
      { name: 'Tom Cruise', profileUrl: 'https://image.tmdb.org/t/p/w500/eOh4ubpOm2Igdg0QH2ghj0mFtC.jpg' },
      { name: 'Hayley Atwell', profileUrl: 'https://image.tmdb.org/t/p/w500/sFxDYkU9Hg7Pk1VN8lCXJsVLX6A.jpg' },
    ],
    director: 'Christopher McQuarrie',
    releaseDate: '2023-07-12',
    status: 'now_showing',
  },
  {
    id: 'm_002',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview: 'Câu chuyện về nhà vật lý J. Robert Oppenheimer và vai trò của ông trong việc phát triển bom nguyên tử.',
    posterUrl: 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/7/0/700x1000-oppen.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    runtime: 180,
    ageRating: 'T16',
    productionCountry: 'US',
    languageType: 'SUBTITLE',
    originalLanguage: 'en',
    spokenLanguages: ['en'],
    genre: [mockGenres[2], mockGenres[3], mockGenres[4]],
    cast: [
      { name: 'Cillian Murphy', profileUrl: 'https://image.tmdb.org/t/p/w500/dm6V24NjjvjMiCtbMkc8Y2WPm2e.jpg' },
      { name: 'Emily Blunt', profileUrl: 'https://image.tmdb.org/t/p/w500/5nCSG5TL4fO28RZqBuSuC7oxLr8.jpg' },
    ],
    director: 'Christopher Nolan',
    releaseDate: '2023-07-21',
    status: 'now_showing',
  },
  {
    id: 'm_003',
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    overview: 'Paul Atreides hợp lực với Chani và Fremen để trả thù những kẻ đã hủy hoại gia đình mình và thực hiện số phận vĩ đại của mình.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    runtime: 166,
    ageRating: 'T13',
    productionCountry: 'US',
    languageType: 'SUBTITLE',
    originalLanguage: 'en',
    spokenLanguages: ['en'],
    genre: [mockGenres[5], mockGenres[6]],
    cast: [
      { name: 'Timothée Chalamet', profileUrl: 'https://image.tmdb.org/t/p/w500/831kFjeVRvbU5N2jZ0YjmY3BLNr.jpg' },
      { name: 'Zendaya', profileUrl: 'https://image.tmdb.org/t/p/w500/b6RuZpWCLCBBIJ0d2uIezLmLAiI.jpg' },
    ],
    director: 'Denis Villeneuve',
    releaseDate: '2024-03-01',
    status: 'upcoming',
  },
];



const now = new Date();
const tomorrow = new Date(now);
tomorrow.setDate(now.getDate() + 1);
const tomorrowISO = tomorrow.toISOString().split('T')[0];

export const mockShowtimes: Showtime[] = [
  {
    id: 'st_001',
    movieId: 'm_001',
    movieReleaseId: 'mr_001',
    cinemaId: 'c_hcm_001', // CGV Landmark 81
    hallId: 'h_lm81_imax', // IMAX Hall
    startTime: `${tomorrowISO}T19:00:00+07:00`,
    endTime: `${tomorrowISO}T21:43:00+07:00`,
    format: 'IMAX',
    language: 'English',
    subtitles: ['Vietnamese'],
    availableSeats: 150,
    totalSeats: 350,
    status: 'SELLING',
    dayType: 'WEEKEND',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'st_002',
    movieId: 'm_002',
    movieReleaseId: 'mr_002',
    cinemaId: 'c_hcm_001', // CGV Landmark 81
    hallId: 'h_lm81_premium', // Premium Hall (changed from VIP)
    startTime: `${tomorrowISO}T20:30:00+07:00`,
    endTime: `${tomorrowISO}T23:30:00+07:00`,
    format: 'TWO_D',
    language: 'English',
    subtitles: ['Vietnamese'],
    availableSeats: 0,
    totalSeats: 50,
    status: 'SELLING',
    dayType: 'WEEKEND',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'st_003',
    movieId: 'm_002',
    movieReleaseId: 'mr_002',
    cinemaId: 'c_hn_002', // Lotte Cinema Cầu Giấy
    hallId: 'h_caugiau_std', // Standard Hall
    startTime: `${tomorrowISO}T17:00:00+07:00`,
    endTime: `${tomorrowISO}T20:00:00+07:00`,
    format: 'TWO_D',
    language: 'Korean',
    subtitles: ['Vietnamese', 'English'],
    availableSeats: 175,
    totalSeats: 180,
    status: 'SELLING',
    dayType: 'WEEKDAY',
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2025-01-01T10:00:00Z',
  },
];


export const mockStaff: Staff[] = [
  {
    id: 's_001',
    name: 'Nguyễn Văn A',
    role: 'Cinema Manager',
    email: 'anv@cinema.com',
    phone: '0901234567',
    hiredAt: '2020-03-01',
    status: 'Active',
    locationId: 'c_hcm_001', // CGV Landmark 81
  },
  {
    id: 's_002',
    name: 'Trần Thị B',
    role: 'Ticketing Staff',
    email: 'btt@cinema.com',
    phone: '0907654321',
    hiredAt: '2022-08-15',
    status: 'Active',
    locationId: 'c_hn_002', // Lotte Cinema Cầu Giấy
  },
  {
    id: 's_003',
    name: 'Lê Văn C',
    role: 'Maintenance Technician',
    email: 'clv@cinema.com',
    phone: '0912345678',
    hiredAt: '2019-01-20',
    status: 'Inactive',
    locationId: 'c_dn_003', // Galaxy Cinema Đà Nẵng (Maintenance)
  },
];